-- V19: Internal zone AI presence intake (append-only raw events)

CREATE TABLE IF NOT EXISTS internal_presence_events (
  presence_event_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  schema_version VARCHAR(32) NOT NULL,
  intake_status ENUM('ACCEPTED','REJECTED') NOT NULL DEFAULT 'ACCEPTED',
  reject_reason_code VARCHAR(64) NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  trace_id VARCHAR(128) NULL,
  camera_code VARCHAR(64) NOT NULL,
  zone_code VARCHAR(32) NOT NULL,
  spot_code VARCHAR(32) NOT NULL,
  plate_compact VARCHAR(32) NULL,
  confidence DECIMAL(6,4) NULL,
  captured_at DATETIME(0) NOT NULL,
  snapshot_object_key VARCHAR(255) NULL,
  model_version VARCHAR(64) NULL,
  site_id BIGINT NULL,
  zone_id BIGINT NULL,
  spot_id BIGINT NULL,
  redis_stream_id VARCHAR(64) NULL,
  raw_event_json JSON NOT NULL,
  created_at DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_internal_presence_events_site FOREIGN KEY (site_id) REFERENCES parking_sites(site_id),
  CONSTRAINT fk_internal_presence_events_zone FOREIGN KEY (zone_id) REFERENCES zones(zone_id),
  CONSTRAINT fk_internal_presence_events_spot FOREIGN KEY (spot_id) REFERENCES spots(spot_id),
  UNIQUE KEY uq_internal_presence_events_idem (idempotency_key),
  UNIQUE KEY uq_internal_presence_events_trace (trace_id),
  KEY ix_internal_presence_events_site_time (site_id, captured_at),
  KEY ix_internal_presence_events_site_spot_time (site_id, spot_id, captured_at),
  KEY ix_internal_presence_events_site_plate_time (site_id, plate_compact, captured_at),
  KEY ix_internal_presence_events_zone_time (zone_id, captured_at),
  KEY ix_internal_presence_events_trace (trace_id),
  KEY ix_internal_presence_events_status_time (intake_status, created_at)
) ENGINE=InnoDB;
