flyway.url=jdbc:mysql://127.0.0.1:3306/parking_mgmt?useSSL=false&allowPublicKeyRetrieval=true
flyway.user=parking_root
flyway.password=RootPassword@123
flyway.locations=filesystem:db/migrations
flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true
