import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

test('source regression: pilot gate, verify rotation và evidence artifact đã được chốt', () => {
  const repoRoot = path.resolve(__dirname, '..', '..', '..', '..')
  const packageJson = JSON.parse(fs.readFileSync(path.join(repoRoot, 'apps', 'api', 'package.json'), 'utf8'))
  const envExample = fs.readFileSync(path.join(repoRoot, 'apps', 'api', '.env.example'), 'utf8')
  const runbook = fs.readFileSync(path.join(repoRoot, 'apps', 'api', 'docs', 'RUNBOOK.md'), 'utf8')
  const securityDoc = fs.readFileSync(path.join(repoRoot, 'apps', 'api', 'docs', 'SECURITY_SECRETS.md'), 'utf8')
  const checklist = fs.readFileSync(path.join(repoRoot, 'apps', 'api', 'docs', 'PILOT_RELEASE_CHECKLIST.md'), 'utf8')
  const changelog = fs.readFileSync(path.join(repoRoot, 'CHANGELOG_BACKEND_PILOT.md'), 'utf8')
  const gateSource = fs.readFileSync(path.join(repoRoot, 'apps', 'api', 'src', 'scripts', 'pilot-gate.ts'), 'utf8')
  const verifySource = fs.readFileSync(path.join(repoRoot, 'apps', 'api', 'src', 'scripts', 'deployment-verify.ts'), 'utf8')
  const rotationCliSource = fs.readFileSync(path.join(repoRoot, 'apps', 'api', 'src', 'scripts', 'secrets-rotation-check.ts'), 'utf8')
  const rotationLibSource = fs.readFileSync(path.join(repoRoot, 'apps', 'api', 'src', 'lib', 'security', 'secret-rotation.ts'), 'utf8')

  assert.equal(packageJson.scripts['pilot:gate'], 'tsx src/scripts/pilot-gate.ts')
  assert.equal(packageJson.scripts['test:pr35'], 'pnpm -s test:pr35:gate && pnpm -s test:pr35:source')
  assert.match(envExample, /PILOT_LABEL=backend-pilot-ready/)
  assert.match(envExample, /PILOT_EVIDENCE_ROOT_DIR=release-evidence\/backend-pilot/)
  assert.match(envExample, /PILOT_VERIFY_DEPLOYMENT_BEFORE_GATE=ON/)
  assert.match(runbook, /pilot:gate/)
  assert.match(runbook, /security-secrets-check\.json/)
  assert.match(runbook, /security-rotation-check\.json/)
  assert.match(runbook, /verify-deployment-pilot\.json/)
  assert.match(securityDoc, /require-active/i)
  assert.match(securityDoc, /pilot:gate/)
  assert.match(checklist, /backend-pilot-ready/)
  assert.match(checklist, /secrets:rotation:check -- --require-active --format json/)
  assert.match(changelog, /BE-PR-35/)
  assert.match(changelog, /backend-pilot-ready/)
  assert.match(gateSource, /security-secrets-check\.json/)
  assert.match(gateSource, /security-rotation-check\.json/)
  assert.match(gateSource, /verify-deployment-pilot\.json/)
  assert.match(gateSource, /pilot-gate-summary\.json/)
  assert.match(gateSource, /test:pr34/)
  assert.match(verifySource, /securityRotation/)
  assert.match(verifySource, /internal-service-rotation/)
  assert.match(verifySource, /device-capture-rotation/)
  assert.match(rotationCliSource, /--require-active/)
  assert.match(rotationLibSource, /missing-active-secret/)
  assert.match(rotationLibSource, /requireActiveEnv/)
})
