import type { AppRole } from './config'

export const ALL_CANONICAL_USER_ROLES: AppRole[] = [
  'SUPER_ADMIN',
  'SITE_ADMIN',
  'MANAGER',
  'CASHIER',
  'GUARD',
  'OPERATOR',
  'VIEWER',
  'WORKER',
]

export const OPS_CONSOLE_ROLES: AppRole[] = ['SITE_ADMIN', 'MANAGER', 'OPERATOR']
export const GUARD_CONSOLE_ROLES: AppRole[] = ['GUARD']
export const CASHIER_CONSOLE_ROLES: AppRole[] = ['CASHIER']
export const VIEWER_CONSOLE_ROLES: AppRole[] = ['VIEWER']

export const ADMIN_OPS_ROLES: AppRole[] = [...OPS_CONSOLE_ROLES]
export const ADMIN_OPS_GUARD_ROLES: AppRole[] = [...ADMIN_OPS_ROLES, ...GUARD_CONSOLE_ROLES]
export const ADMIN_OPS_WORKER_ROLES: AppRole[] = [...ADMIN_OPS_ROLES]
export const ADMIN_OPS_GUARD_WORKER_ROLES: AppRole[] = [...ADMIN_OPS_GUARD_ROLES]
export const ADMIN_OPS_GUARD_CASHIER_WORKER_ROLES: AppRole[] = [...ADMIN_OPS_GUARD_ROLES, ...CASHIER_CONSOLE_ROLES]
export const ADMIN_OPS_CASHIER_ROLES: AppRole[] = [...ADMIN_OPS_ROLES, ...CASHIER_CONSOLE_ROLES]

export const DASHBOARD_READ_ROLES: AppRole[] = [...ADMIN_OPS_GUARD_CASHIER_WORKER_ROLES, 'WORKER', ...VIEWER_CONSOLE_ROLES]
export const SESSION_READ_ROLES: AppRole[] = [...ADMIN_OPS_GUARD_WORKER_ROLES, ...VIEWER_CONSOLE_ROLES]
export const GATE_MONITOR_READ_ROLES: AppRole[] = [...ADMIN_OPS_GUARD_WORKER_ROLES, ...VIEWER_CONSOLE_ROLES]
export const PARKING_LIVE_READ_ROLES: AppRole[] = [...ADMIN_OPS_GUARD_ROLES, ...VIEWER_CONSOLE_ROLES]
